In [ ]:
import numpy as np

In [64]:
#1. Create a null array of size 10 but the fifth value which is 1

nullList = [None] * 10
nullList[4] = 1
print (np.array(nullList))


[None None None None 1 None None None None None]


In [32]:
#2. Reverse a above created array (first element becomes last)


list1 = [0,1,2,3,4,5,6,7,8,9]
j = len(list1) - 1
#reverseList = [None] * j
print (list1)
#print (reversed(list1))
reverseList = list1[:: -1] # what is :

    
print (np.array(reverseList))



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9 8 7 6 5 4 3 2 1 0]


In [36]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
#arange and reshape
matrixArray = np.arange(9).reshape(3,3)
print(matrixArray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [112]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]

npArray = np.array([1,2,0,0,4,0])
print (npArray)
print(np.nonzero(npArray))
print(np.where(npArray != 0)[0]) #boolean array

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [49]:
#5. Create a 3x3x3 array with random values
#np.random.random(3)

randomArr = np.random.random(size=(3,3))
print (randomArr)

[[0.58653712 0.11147733 0.90295137]
 [0.00141086 0.3024649  0.2397256 ]
 [0.43957129 0.48785221 0.92830111]]


In [88]:
#6. Create a 10x10 array with random values and find the minimum and maximum values

ranArr = np.random.randint(low=15,high=150, size=(10,10))
print (ranArr)

#min
minVal = np.min(ranArr)
print('min val')
print(minVal)
#max
maxVal = np.max(ranArr)
print('max val')
print(maxVal)

[[145  22  40  73  39  31  15  32  83  33]
 [ 67  91  27  35 113 115  91  19  65  47]
 [ 58  42  35 145 128  23  46  28  56  19]
 [134 129 106  91 135 140  37  26  49  65]
 [ 89 131 100 125  56 107 105  91  55  94]
 [ 85 146 101 114  19  31  20  25  51  69]
 [ 60  98 122  32  68 109 109  20  67  29]
 [ 42  93  56 101  24  23  61  40 149 112]
 [ 47  70 125  42  46  34 126 147 125 124]
 [ 95 147  95  84  64  67 113  34 110  63]]
min val
15
max val
149


In [114]:
#7. Create a random vector of size 30 and find the mean value

testVector = np.random.random(30)
print(testVector)
print(np.mean(testVector))

[0.0836084  0.23720949 0.71044693 0.41387301 0.35790188 0.34283477
 0.55848034 0.25428979 0.69613915 0.84849965 0.12292982 0.92950494
 0.63580024 0.1197492  0.63493429 0.68400892 0.81755154 0.03362766
 0.38426592 0.54033581 0.04670356 0.5175158  0.66327544 0.61938394
 0.89114234 0.67012748 0.32213917 0.07616656 0.17130704 0.30364352]
0.4562465530570814


In [121]:
#8. Create a 2d array with 1 on the border and 0 inside

arr = np.ones((5,5)) # array of ones
print("original array")
print(arr)
#arr[1:-1]= 0

print("decorated array")
arr[1:-1, 1:-1] = 0
print(arr)


def border_array(m, n):
    arr = np.zeros((m, n))
    arr[0] = 1
    arr[-1] = 1
    arr[:,0] = 1
    arr[:, -1] =1
    return arr

print(border_array(10, 10))

original array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
decorated array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

arr53 = np.random.random(size=(5,3))
print("array 5 x 3")
print(arr53)
print("array 3 x 2")
arr32 = np.random.random(size=(3,2))
print(arr32)

arrmulti = np.dot(arr53, arr32)
print("arrayproduct")
print(arrmulti)

array 5 x 3
[[0.3847015  0.91501485 0.64717481]
 [0.20468086 0.48359462 0.70629949]
 [0.32697969 0.37178329 0.13996332]
 [0.61904547 0.34239293 0.50192561]
 [0.67699956 0.24269142 0.60531423]]
array 3 x 2
[[0.38108379 0.23092281]
 [0.26189485 0.07659725]
 [0.31951031 0.63535472]]
array multiple
[[0.59302021 0.57010954]
 [0.43032147 0.53305821]
 [0.26669451 0.192911  ]
 [0.48594955 0.48807888]
 [0.51495733 0.55951339]]


In [122]:
#10. Extract the integer part of a random array
arr77 = np.random.random(size=(7,7))
print (arr77)
print("Integer Part 1")

print(np.trunc(arr77))

print(np.rint(arr77))

print("Integer Part 2")
arrInt = np.ceil(arr77)
print(arrInt)

print("Integer Part 3")
print(np.floor(arr77))


[[0.52327598 0.58981415 0.23165719 0.84632964 0.80852157 0.37647988
  0.93360992]
 [0.21814171 0.3246802  0.45518113 0.77764639 0.02008025 0.4281815
  0.51036011]
 [0.71013764 0.1584939  0.10309694 0.64268164 0.02927316 0.67060726
  0.64259187]
 [0.65347999 0.6610821  0.49001679 0.46831183 0.72136191 0.46673191
  0.1562324 ]
 [0.08253129 0.76673182 0.93535769 0.79207066 0.77655754 0.77008543
  0.79948128]
 [0.95514296 0.3742586  0.55046778 0.43440886 0.71576407 0.19413464
  0.25553077]
 [0.82907328 0.35326289 0.41798851 0.00396509 0.1180566  0.60635917
  0.75370277]]
Integer Part 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1.]]
Integer Part 2
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1.

In [99]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4
arr55 = np.zeros((5,5))
print("Original array")
print(arr55)
print("values 0 - 4")
arr55 += np.arange(5) #really sleek
print(arr55)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [101]:
#12.  Create a random vector of size 10 and sort it
arr10 = np.random.random(size=(10))
print (arr10)

print('sorted array')
print(np.sort(arr10))

[0.18106074 0.79987367 0.55458437 0.5450145  0.70860615 0.71020357
 0.49074407 0.1395082  0.1620909  0.76932913]
sorted array
[0.1395082  0.1620909  0.18106074 0.49074407 0.5450145  0.55458437
 0.70860615 0.71020357 0.76932913 0.79987367]


In [105]:
#13. Consider two random array A anb B, check if they are equal.
arr1 = np.random.random(size=(10))

print(arr1)

arr2 =  np.random.random(size=(10))
print(arr2)

print(np.equal(arr1,arr2))
#np.allclose -- floats


[0.90558439 0.24935415 0.19790696 0.3517982  0.13900826 0.93504019
 0.07115642 0.30625983 0.14031597 0.7573948 ]
[0.10824745 0.86237668 0.40065827 0.03831933 0.26902125 0.99934616
 0.49205015 0.16817808 0.44994164 0.94782944]
[False False False False False False False False False False]


In [123]:
#14. How to tell if a given 2D array has null columns?

arr14 = np.random.random(size=(5,4))



print(arr14)
print((~arr14.any(axis=0)).any())

#arr0 = np.array([None]*10)
#print((~arr0.any(axis=0)).any()) #errors out

[[0.78091368 0.37310676 0.67854992 0.75616753]
 [0.3023582  0.63150545 0.51170556 0.95626163]
 [0.94452469 0.45229395 0.25488334 0.46862733]
 [0.75914747 0.23042134 0.7200979  0.44491282]
 [0.44351811 0.59587849 0.95392583 0.41551162]]
False


In [126]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?
arr14 = np.random.randn(3,4,5,6)
print(arr14.shape)

print(np.sum(arr14, axis=(2,3)))

(3, 4, 5, 6)
[[-4.03308756  1.81251023 -4.57573632  3.53972877]
 [-6.62369107  8.28363332 -0.38881834  5.16435543]
 [-6.27695752  8.98092956  5.19164499 -3.66815411]]


In [127]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#Question: I'm not sure if this is right. I tried different things, but taking the outer product of
#arrays with non-equal dimensions seems to work. I did not find a solution in the videos or in the notebook, so
#I tried to find something online.

array553 = np.random.randn(5,5,3)
array55 = np.random.randn(5,5)
product = np.outer(array553, array55)

print(product)

[[ 0.42061143 -0.45337624 -0.80134731 ...  0.75335607  0.03020029
   0.1366816 ]
 [-0.08640175  0.09313228  0.16461229 ... -0.15475396 -0.00620373
  -0.02807705]
 [ 0.35872272 -0.38666651 -0.68343716 ...  0.64250735  0.02575662
   0.11657029]
 ...
 [-1.43791267  1.54992323  2.73950576 ... -2.57544173 -0.10324346
  -0.4672631 ]
 [-0.54313916  0.58544863  1.03478666 ... -0.97281516 -0.03899789
  -0.17649812]
 [ 0.46006886 -0.49590732 -0.87652145 ...  0.82402817  0.03303337
   0.14950366]]


In [129]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
#CONFUSED: Outside of my understanding from the lectures. Sorry. I can make the matrix but not sure how 
#to get the 'blocks'
# 

# np.lib.stride_tricks.as_strided()
def contiguous_3x3_blocks(a):
    m, n = a.shape
    return [a[i:i+3, j:j+3] for i in range(m-2) for j in range(n-2)]

a = np.arange(20).reshape(4,5)
print(a)

for block in contiguous_3x3_blocks(a):
    print(block)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]
[[ 5  6  7]
 [10 11 12]
 [15 16 17]]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [132]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

#reduceat

a = np.ones((16,16))
n = 4
print("Array 16x16:")
print(a)
result = np.add.reduceat(np.add.reduceat(a,np.arange(0, a.shape[0], n), axis=0), np.arange(0, a.shape[1], n), axis=1)

print(result)


Array 16x16:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [111]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences
# scipy to do t-test

from scipy import stats

g1 = np.random.normal(0,1,100)
g2 = np.random.normal(1,1,100)

print(g1)

print("--------------")
print(g2)

print("--------------")

testRslt = stats.ttest_ind(g1,g2)
print(testRslt)

[ 0.81195819  1.0239203  -0.45119331  0.90431405 -0.08010095  1.0753382
  0.85067058 -1.18912607 -0.70339243 -1.68206019 -1.1048709   0.02747066
  0.23357073  1.02389266  0.13857036 -0.29792548  0.56428214  0.30533295
 -1.10736894  0.10844071 -1.82029169 -0.35596808  0.85921228 -0.55610718
  0.0153098   0.00621012  0.26007322 -0.64769802  1.22405854 -0.06868117
  0.53343372  0.95066583  2.32623687 -0.69335602  0.7982886   1.12509833
 -2.02336046  0.75271105  0.20854418 -0.10749134 -2.65477719  0.65430559
 -0.86338898  1.8129669   0.1278231  -0.02427737  0.32523844 -0.88277844
  0.15476046 -0.80893709  0.7975639   0.63336606  0.20337389  1.45502979
  0.54754291 -1.00954266  0.70099934 -0.71477688 -1.41001183  0.41917129
  2.03852377 -0.36147657 -2.40632342 -0.95645124 -0.3196202   0.25731027
 -0.95505553 -1.79691299 -0.83792752 -0.92405311  0.38610102 -1.00126307
  0.88371032  1.76644296 -0.38744338  1.7335595  -0.71264383 -2.48955113
  0.00423014 -0.16032018  2.17840635 -0.78062601 -0.